<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="TinyMenu.Example.config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup />

  <ItemGroup>
    <ProjectReference Include="..\TinyMenu.Core\TinyMenu.Core.fsproj" />
  </ItemGroup>

</Project>
